image: ruby:2.4.1

pipelines:
  default:
    - step:
        script:
          - git archive --remote=git@bitbucket.org:guideinvestimentos/rails_defaults.git HEAD .rubocop.yml | tar -x
          - bundle install
          - mv .env.pipelines .env
          - gem install rubocop
          - rspec -fdoc
          - rubocop .
  branches:
    master:
      - step:
          script:
            - gem build wso2_toolbox.gemspec
            - curl -u $RUBYGEMS_USERNAME:$RUBYGEMS_PASSWORD https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials
            - chmod 0600 ~/.gem/credentials
            - gem push $(ls *.gem)
